<a href="https://colab.research.google.com/github/Mark-Soucek/CHE4061_Fall2025/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
from plotly.subplots import make_subplots
from scipy.optimize import minimize

In [10]:
#When we minimize the deviation between our approximation and data vector, we are instinctively making the error #perpendicular not just to approximation but to the plane defined by the basis vectors. Therefore, the error is #perpendicular to each of the basis vectors.

In [11]:
x=np.linspace(0,10,21)
y=2*x + 1
y=y+np.random.normal(loc=0, scale=0.75, size=y.size)

In [12]:
def sse(v):
    m, b = v
    ymodel = m*x + b
    return np.sum((ymodel-y)**2)

In [13]:
minimize(sse, [1, 0.5])

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 17.046308007809042
        x: [ 1.989e+00  8.145e-01]
      nit: 4
      jac: [ 4.768e-07  2.384e-07]
 hess_inv: [[ 2.597e-03 -1.299e-02]
            [-1.299e-02  8.874e-02]]
     nfev: 18
     njev: 6

In [14]:
A = np.c_[x, np.ones_like(x)]

In [15]:
A.T @ A

array([[717.5, 105. ],
       [105. ,  21. ]])

In [16]:
A.T @ y

array([1512.70332389,  225.96033014])

In [17]:
c=np.linalg.solve(A.T @ A, A.T @ y)

In [18]:
fig=make_subplots()
fig.add_scatter(x=x, y=y, mode='markers')
fig.add_scatter(x=x, y=A @ c, mode='lines')
fig.update_layout(width=600, height=400,template='plotly_dark')

In [27]:
x=np.linspace(-2, 2, 51)
y = (x+1.7)*(x-0.1)*(x-1.7)
y=y+np.random.normal(loc=0, scale=0.5, size=y.size)

In [28]:
fig=make_subplots()
fig.add_scatter(x=x, y=y, mode='markers')
fig.add_scatter(x=x, y=A @ c, mode='lines')
fig.update_layout(width=600, height=400,template='plotly_dark')

In [21]:
A = np.c_[x**3, x**2, x, np.ones_like(x)]


In [22]:
c=np.linalg.solve(A.T @ A, A.T @ y)

In [ ]:
#Antoine Equation:
#Log10 P = A - (B/(T+C))
#Log10 P = (A(T+C)-B)/(T+C)
#TLog10 P + CLog10 P = (AT+AC)-B)
#TLog10 P = AT+(AC-B) - CLog10 P

[T1 -log10P1  1]            [T1Log10P1]
[T2 -log10P2  1]  [A]       [T1Log10P2]
[T3 -log10P3  1]  [C]       [.]
[.  .         1]  [AC_B]    [.]
[.  .         1]            [T1Log10Pn]
[Tn -log10Pn  1]
        A